ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS `heroku_864d8a7fa6a6bdf`.`DEPARTMENT` (
    `DEPT_ID` INT AUTO_INCREMENT NOT NULL,
    `DEPT_NAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`DEPT_ID`)
);

CREATE TABLE IF NOT EXISTS `heroku_864d8a7fa6a6bdf`.`EMPLOYEE` (
    `EMPLOYEE_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `FIRST_NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `GENDER` VARCHAR(6) NOT NULL,
    `PASSWORD` VARCHAR(256) NOT NULL,
    `DEPT_ID` INT,
    `PUBLIC_EXPOSURE` BOOLEAN,
    `AGE` INT,
    FOREIGN KEY (`DEPT_ID`) REFERENCES `DEPARTMENT`(`DEPT_ID`)
);

CREATE TABLE IF NOT EXISTS `heroku_864d8a7fa6a6bdf`.`COVID` (
    `EMPLOYEE_ID` INT NOT NULL,
    `SHORT_BREATH` VARCHAR(5) NOT NULL,
    `DRY_COUGH` VARCHAR(5) NOT NULL,
    `TEMP` VARCHAR(5) NOT NULL,
    `FATIGUE` VARCHAR(5) NOT NULL,
    `PREGNANT` VARCHAR(5) NOT NULL,
    `PERCENTAGE` DECIMAL,
    `ZONE` VARCHAR(10),
    FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`)
);

CREATE TABLE `heroku_864d8a7fa6a6bdf`.`suspects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` INT NOT NULL,
  `SUSPECT_ID` INT NOT NULL,
  PRIMARY KEY (`id`)
  );
